version: '3.8'

services:
  db:
    container_name: db
    image: registry.gigwork.ru/docker/postgresql-v134
    restart: always
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data/pgdata"
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 15432:5432

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - XDEBUG_SESSION=PHPSTORM
    volumes:
      - ./:/var/www
      - ./logs:/var/logs
    tty: true
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"


