api_controllers:
    resource: '../../src/UI/Http/Rest/Controller/'
    type: annotation
    prefix: /api

web_controllers:
    resource: '../../src/UI/Http/Web/Controller/'
    type: annotation

kernel:
    resource: ../../src/App/Shared/Infrastructure/Kernel.php
    type: annotation
