doctrine:
    dbal:
        schema_filter: ~^(?!event)~ # this will ignore broadway event store table
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_postgresql'
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        server_version: '12'
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
            email: App\Shared\Infrastructure\Persistence\Doctrine\Types\EmailType
            hashed_password: App\Shared\Infrastructure\Persistence\Doctrine\Types\HashedPasswordType
        mapping_types:
            uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/Domain/Auth/'
                prefix: 'App\Domain\Auth\Entity'
            App\Domain\Order:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/Domain/Order/'
                prefix: 'App\Domain\Order\Entity'
