index:
    path: /
    controller: UI\Http\Web\Controller\DefaultController::index
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
api_controllers:
  resource: '../src/UI/Http/Rest/Controller/'
  type: annotation
  prefix: /api

web_controllers:
  resource: '../src/UI/Http/Web/Controller/'
  type: annotation

  